import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import { Toaster } from "@/components/ui/toaster";
import clsx from "clsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Data Ingestion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "min-h-screen flex flex-col")}>
        <Navigation />
        <main className={clsx("p-8 flex flex-col items-center flex-grow")}>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
